#!/bin/sh
### BEGIN INIT INFO
# Provides:		logwall
# Required-Start:	$syslog
# Required-Stop:	$syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	syslog firewall
### END INIT INFO
#

PATH=/bin:/usr/bin:/sbin:/usr/sbin
PROGNAME="logwall"
SUPERVISOR=""
DAEMON="/usr/sbin/$PROGNAME"
OPTIONS="-q"
PIDFILE="/var/run/$PROGNAME.pid"
DESC="Syslog Firewall"

test -x "$DAEMON" || exit 0
. /lib/lsb/init-functions

test -f /etc/default/$PROGNAME && . /etc/default/$PROGNAME
PID=$(cat "$PIDFILE" 2>/dev/null)
[ ! -d "/proc/$PID" ] && PID=""


case "$1" in
  start)
  	if [ -n "$PID" ]; then
  		echo "$DESC is already running." >&2
  		exit 1
  	else
		log_daemon_msg "Starting $DESC"
		$SUPERVISOR $DAEMON -P "$PIDFILE" $OPTIONS
		log_end_msg $?
	fi
    ;;
  stop)
  	if [ -n "$PID" ]; then
		log_daemon_msg "Stopping $DESC"
		kill -INT $PID
		log_end_msg $?
	else
		echo "$DESC is not running." >&2
  		exit 1
	fi
    ;;
  reload)
  	if [ -n "$PID" ]; then
		log_daemon_msg "Soft stopping $DESC"
		kill -HUP $PID
		ok=$?
		if [ $ok = 0 ]; then
			while [ -s "$PIDFILE" ]; do
				sleep 1
				echo -n .
			done
		fi
		log_end_msg $ok
	else
		ok=0
	fi
	if [ $ok = 0 ]; then
		$0 start
	fi
    ;;
  restart)
	$0 stop
	$0 start
    ;;
  status)
	status_of_proc -p "$PIDFILE" "$DAEMON" "$PROGNAME"
    ;;
  *)
	echo "Usage: $0 {start|stop|reload|restart|status}"
	exit 1
    ;;
esac

